/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.iana.mediatypes;

import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Media Types and Subtypes (formerly known as MIME types) will be assigned and
 * listed by the IANA
 * @see http://www.iana.org/assignments/media-types/media-types.xml
 *
 * @author Miroslav Nachev [mnachev@gmail.com]
 */
public enum Media {

    ApplicationAndrewInset("application/andrew-inset", "ez"),
    ApplicationApplixware("application/applixware", "aw"),
    ApplicationAtomXml("application/atom+xml", "atom"),
    ApplicationAtomcatXml("application/atomcat+xml", "atomcat"),
    ApplicationAtomsvcXml("application/atomsvc+xml", "atomsvc"),
    ApplicationCcxmlXml("application/ccxml+xml", "ccxml"),
    ApplicationCdmiCapability("application/cdmi-capability", "cdmia"),
    ApplicationCdmiContainer("application/cdmi-container", "cdmic"),
    ApplicationCdmiDomain("application/cdmi-domain", "cdmid"),
    ApplicationCdmiObject("application/cdmi-object", "cdmio"),
    ApplicationCdmiQueue("application/cdmi-queue", "cdmiq"),
    ApplicationCuSeeme("application/cu-seeme", "cu"),
    ApplicationDavmountXml("application/davmount+xml", "davmount"),
    ApplicationDocbookXml("application/docbook+xml", "dbk"),
    ApplicationDsscDer("application/dssc+der", "dssc"),
    ApplicationDsscXml("application/dssc+xml", "xdssc"),
    ApplicationEcmascript("application/ecmascript", "ecma"),
    ApplicationEmmaXml("application/emma+xml", "emma"),
    ApplicationEpubZip("application/epub+zip", "epub"),
    ApplicationExi("application/exi", "exi"),
    ApplicationFontTdpfr("application/font-tdpfr", "pfr"),
    ApplicationFontWoff("application/font-woff", "woff"),
    ApplicationGmlXml("application/gml+xml", "gml"),
    ApplicationGpxXml("application/gpx+xml", "gpx"),
    ApplicationGxf("application/gxf", "gxf"),
    ApplicationHyperstudio("application/hyperstudio", "stk"),
    ApplicationInkmlXml("application/inkml+xml", "ink", "inkml"),
    ApplicationIpfix("application/ipfix", "ipfix"),
    ApplicationJavaArchive("application/java-archive", "jar"),
    ApplicationJavascript("application/javascript", "js"),
    ApplicationJavaSerializedObject("application/java-serialized-object", "ser"),
    ApplicationJavaVm("application/java-vm", "class"),
    ApplicationJson("application/json", "json"),
    ApplicationJsonmlJson("application/jsonml+json", "jsonml"),
    ApplicationLostXml("application/lost+xml", "lostxml"),
    ApplicationMacBinhex40("application/mac-binhex40", "hqx"),
    ApplicationMacCompactpro("application/mac-compactpro", "cpt"),
    ApplicationMadsXml("application/mads+xml", "mads"),
    ApplicationMarc("application/marc", "mrc"),
    ApplicationMarcxmlXml("application/marcxml+xml", "mrcx"),
    ApplicationMathematica("application/mathematica", "ma", "nb", "mb"),
    ApplicationMathmlXml("application/mathml+xml", "mathml"),
    ApplicationMbox("application/mbox", "mbox"),
    ApplicationMediaservercontrolXml("application/mediaservercontrol+xml", "mscml"),
    ApplicationMetalinkXml("application/metalink+xml", "metalink"),
    ApplicationMetalink4Xml("application/metalink4+xml", "meta4"),
    ApplicationMetsXml("application/mets+xml", "mets"),
    ApplicationModsXml("application/mods+xml", "mods"),
    ApplicationMp21("application/mp21", "m21", "mp21"),
    ApplicationMp4("application/mp4", "mp4s"),
    ApplicationMsword("application/msword", "doc", "dot"),
    ApplicationMxf("application/mxf", "mxf"),
    ApplicationOctetStream("application/octet-stream", "bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy"),
    ApplicationOda("application/oda", "oda"),
    ApplicationOebpsPackageXml("application/oebps-package+xml", "opf"),
    ApplicationOgg("application/ogg", "ogx"),
    ApplicationOmdocXml("application/omdoc+xml", "omdoc"),
    ApplicationOnenote("application/onenote", "onetoc", "onetoc2", "onetmp", "onepkg"),
    ApplicationOxps("application/oxps", "oxps"),
    ApplicationPatchOpsErrorXml("application/patch-ops-error+xml", "xer"),
    ApplicationPdf("application/pdf", "pdf"),
    ApplicationPgpEncrypted("application/pgp-encrypted", "pgp"),
    ApplicationPgpSignature("application/pgp-signature", "asc", "sig"),
    ApplicationPicsRules("application/pics-rules", "prf"),
    ApplicationPkcs10("application/pkcs10", "p10"),
    ApplicationPkcs7Mime("application/pkcs7-mime", "p7m", "p7c"),
    ApplicationPkcs7Signature("application/pkcs7-signature", "p7s"),
    ApplicationPkcs8("application/pkcs8", "p8"),
    ApplicationPkixAttrCert("application/pkix-attr-cert", "ac"),
    ApplicationPkixCert("application/pkix-cert", "cer"),
    ApplicationPkixcmp("application/pkixcmp", "pki"),
    ApplicationPkixCrl("application/pkix-crl", "crl"),
    ApplicationPkixPkipath("application/pkix-pkipath", "pkipath"),
    ApplicationPlsXml("application/pls+xml", "pls"),
    ApplicationPostscript("application/postscript", "ai", "eps", "ps"),
    ApplicationPrsCww("application/prs.cww", "cww"),
    ApplicationPskcXml("application/pskc+xml", "pskcxml"),
    ApplicationRdfXml("application/rdf+xml", "rdf"),
    ApplicationReginfoXml("application/reginfo+xml", "rif"),
    ApplicationRelaxNgCompactSyntax("application/relax-ng-compact-syntax", "rnc"),
    ApplicationResourceListsXml("application/resource-lists+xml", "rl"),
    ApplicationResourceListsDiffXml("application/resource-lists-diff+xml", "rld"),
    ApplicationRlsServicesXml("application/rls-services+xml", "rs"),
    ApplicationRpkiGhostbusters("application/rpki-ghostbusters", "gbr"),
    ApplicationRpkiManifest("application/rpki-manifest", "mft"),
    ApplicationRpkiRoa("application/rpki-roa", "roa"),
    ApplicationRsdXml("application/rsd+xml", "rsd"),
    ApplicationRssXml("application/rss+xml", "rss"),
    ApplicationRtf("application/rtf", "rtf"),
    ApplicationSbmlXml("application/sbml+xml", "sbml"),
    ApplicationScvpCvRequest("application/scvp-cv-request", "scq"),
    ApplicationScvpCvResponse("application/scvp-cv-response", "scs"),
    ApplicationScvpVpRequest("application/scvp-vp-request", "spq"),
    ApplicationScvpVpResponse("application/scvp-vp-response", "spp"),
    ApplicationSdp("application/sdp", "sdp"),
    ApplicationSetPaymentInitiation("application/set-payment-initiation", "setpay"),
    ApplicationSetRegistrationInitiation("application/set-registration-initiation", "setreg"),
    ApplicationShfXml("application/shf+xml", "shf"),
    ApplicationSmilXml("application/smil+xml", "smi", "smil"),
    ApplicationSparqlQuery("application/sparql-query", "rq"),
    ApplicationSparqlResultsXml("application/sparql-results+xml", "srx"),
    ApplicationSrgs("application/srgs", "gram"),
    ApplicationSrgsXml("application/srgs+xml", "grxml"),
    ApplicationSruXml("application/sru+xml", "sru"),
    ApplicationSsdlXml("application/ssdl+xml", "ssdl"),
    ApplicationSsmlXml("application/ssml+xml", "ssml"),
    ApplicationTeiXml("application/tei+xml", "tei", "teicorpus"),
    ApplicationThraudXml("application/thraud+xml", "tfi"),
    ApplicationTimestampedData("application/timestamped-data", "tsd"),
    ApplicationVnd3gppPicBwLarge("application/vnd.3gpp.pic-bw-large", "plb"),
    ApplicationVnd3gppPicBwSmall("application/vnd.3gpp.pic-bw-small", "psb"),
    ApplicationVnd3gppPicBwVar("application/vnd.3gpp.pic-bw-var", "pvb"),
    ApplicationVnd3gpp2Tcap("application/vnd.3gpp2.tcap", "tcap"),
    ApplicationVnd3mPostItNotes("application/vnd.3m.post-it-notes", "pwn"),
    ApplicationVndAccpacSimplyAso("application/vnd.accpac.simply.aso", "aso"),
    ApplicationVndAccpacSimplyImp("application/vnd.accpac.simply.imp", "imp"),
    ApplicationVndAcucobol("application/vnd.acucobol", "acu"),
    ApplicationVndAcucorp("application/vnd.acucorp", "atc", "acutc"),
    ApplicationVndAdobeAirApplicationInstallerPackageZip("application/vnd.adobe.air-application-installer-package+zip", "air"),
    ApplicationVndAdobeFormscentralFcdt("application/vnd.adobe.formscentral.fcdt", "fcdt"),
    ApplicationVndAdobeFxp("application/vnd.adobe.fxp", "fxp", "fxpl"),
    ApplicationVndAdobeXdpXml("application/vnd.adobe.xdp+xml", "xdp"),
    ApplicationVndAdobeXfdf("application/vnd.adobe.xfdf", "xfdf"),
    ApplicationVndAheadSpace("application/vnd.ahead.space", "ahead"),
    ApplicationVndAirzipFilesecureAzf("application/vnd.airzip.filesecure.azf", "azf"),
    ApplicationVndAirzipFilesecureAzs("application/vnd.airzip.filesecure.azs", "azs"),
    ApplicationVndAmazonEbook("application/vnd.amazon.ebook", "azw"),
    ApplicationVndAmericandynamicsAcc("application/vnd.americandynamics.acc", "acc"),
    ApplicationVndAmigaAmi("application/vnd.amiga.ami", "ami"),
    ApplicationVndAndroidPackageArchive("application/vnd.android.package-archive", "apk"),
    ApplicationVndAnserWebCertificateIssueInitiation("application/vnd.anser-web-certificate-issue-initiation", "cii"),
    ApplicationVndAnserWebFundsTransferInitiation("application/vnd.anser-web-funds-transfer-initiation", "fti"),
    ApplicationVndAntixGameComponent("application/vnd.antix.game-component", "atx"),
    ApplicationVndAppleInstallerXml("application/vnd.apple.installer+xml", "mpkg"),
    ApplicationVndAppleMpegurl("application/vnd.apple.mpegurl", "m3u8"),
    ApplicationVndAristanetworksSwi("application/vnd.aristanetworks.swi", "swi"),
    ApplicationVndAstraeaSoftwareIota("application/vnd.astraea-software.iota", "iota"),
    ApplicationVndAudiograph("application/vnd.audiograph", "aep"),
    ApplicationVndBlueiceMultipass("application/vnd.blueice.multipass", "mpm"),
    ApplicationVndBmi("application/vnd.bmi", "bmi"),
    ApplicationVndBusinessobjects("application/vnd.businessobjects", "rep"),
    ApplicationVndChemdrawXml("application/vnd.chemdraw+xml", "cdxml"),
    ApplicationVndChipnutsKaraokeMmd("application/vnd.chipnuts.karaoke-mmd", "mmd"),
    ApplicationVndCinderella("application/vnd.cinderella", "cdy"),
    ApplicationVndClaymore("application/vnd.claymore", "cla"),
    ApplicationVndCloantoRp9("application/vnd.cloanto.rp9", "rp9"),
    ApplicationVndClonkC4group("application/vnd.clonk.c4group", "c4g", "c4d", "c4f", "c4p", "c4u"),
    ApplicationVndCluetrustCartomobileConfig("application/vnd.cluetrust.cartomobile-config", "c11amc"),
    ApplicationVndCluetrustCartomobileConfigPkg("application/vnd.cluetrust.cartomobile-config-pkg", "c11amz"),
    ApplicationVndCommonspace("application/vnd.commonspace", "csp"),
    ApplicationVndContactCmsg("application/vnd.contact.cmsg", "cdbcmsg"),
    ApplicationVndCosmocaller("application/vnd.cosmocaller", "cmc"),
    ApplicationVndCrickClicker("application/vnd.crick.clicker", "clkx"),
    ApplicationVndCrickClickerKeyboard("application/vnd.crick.clicker.keyboard", "clkk"),
    ApplicationVndCrickClickerPalette("application/vnd.crick.clicker.palette", "clkp"),
    ApplicationVndCrickClickerTemplate("application/vnd.crick.clicker.template", "clkt"),
    ApplicationVndCrickClickerWordbank("application/vnd.crick.clicker.wordbank", "clkw"),
    ApplicationVndCriticaltoolsWbsXml("application/vnd.criticaltools.wbs+xml", "wbs"),
    ApplicationVndCtcPosml("application/vnd.ctc-posml", "pml"),
    ApplicationVndCupsPpd("application/vnd.cups-ppd", "ppd"),
    ApplicationVndCurlCar("application/vnd.curl.car", "car"),
    ApplicationVndCurlPcurl("application/vnd.curl.pcurl", "pcurl"),
    ApplicationVndDart("application/vnd.dart", "dart"),
    ApplicationVndDataVisionRdz("application/vnd.data-vision.rdz", "rdz"),
    ApplicationVndDeceData("application/vnd.dece.data", "uvf", "uvvf", "uvd", "uvvd"),
    ApplicationVndDeceTtmlXml("application/vnd.dece.ttml+xml", "uvt", "uvvt"),
    ApplicationVndDeceUnspecified("application/vnd.dece.unspecified", "uvx", "uvvx"),
    ApplicationVndDeceZip("application/vnd.dece.zip", "uvz", "uvvz"),
    ApplicationVndDenovoFcselayoutLink("application/vnd.denovo.fcselayout-link", "fe_launch"),
    ApplicationVndDna("application/vnd.dna", "dna"),
    ApplicationVndDolbyMlp("application/vnd.dolby.mlp", "mlp"),
    ApplicationVndDpgraph("application/vnd.dpgraph", "dpg"),
    ApplicationVndDreamfactory("application/vnd.dreamfactory", "dfac"),
    ApplicationVndDsKeypoint("application/vnd.ds-keypoint", "kpxx"),
    ApplicationVndDvbAit("application/vnd.dvb.ait", "ait"),
    ApplicationVndDvbService("application/vnd.dvb.service", "svc"),
    ApplicationVndDynageo("application/vnd.dynageo", "geo"),
    ApplicationVndEcowinChart("application/vnd.ecowin.chart", "mag"),
    ApplicationVndEnliven("application/vnd.enliven", "nml"),
    ApplicationVndEpsonEsf("application/vnd.epson.esf", "esf"),
    ApplicationVndEpsonMsf("application/vnd.epson.msf", "msf"),
    ApplicationVndEpsonQuickanime("application/vnd.epson.quickanime", "qam"),
    ApplicationVndEpsonSalt("application/vnd.epson.salt", "slt"),
    ApplicationVndEpsonSsf("application/vnd.epson.ssf", "ssf"),
    ApplicationVndEszigno3Xml("application/vnd.eszigno3+xml", "es3", "et3"),
    ApplicationVndEzpixAlbum("application/vnd.ezpix-album", "ez2"),
    ApplicationVndEzpixPackage("application/vnd.ezpix-package", "ez3"),
    ApplicationVndFdf("application/vnd.fdf", "fdf"),
    ApplicationVndFdsnMseed("application/vnd.fdsn.mseed", "mseed"),
    ApplicationVndFdsnSeed("application/vnd.fdsn.seed", "seed", "dataless"),
    ApplicationVndFlographit("application/vnd.flographit", "gph"),
    ApplicationVndFluxtimeClip("application/vnd.fluxtime.clip", "ftc"),
    ApplicationVndFramemaker("application/vnd.framemaker", "fm", "frame", "maker", "book"),
    ApplicationVndFrogansFnc("application/vnd.frogans.fnc", "fnc"),
    ApplicationVndFrogansLtf("application/vnd.frogans.ltf", "ltf"),
    ApplicationVndFscWeblaunch("application/vnd.fsc.weblaunch", "fsc"),
    ApplicationVndFujitsuOasys("application/vnd.fujitsu.oasys", "oas"),
    ApplicationVndFujitsuOasys2("application/vnd.fujitsu.oasys2", "oa2"),
    ApplicationVndFujitsuOasys3("application/vnd.fujitsu.oasys3", "oa3"),
    ApplicationVndFujitsuOasysgp("application/vnd.fujitsu.oasysgp", "fg5"),
    ApplicationVndFujitsuOasysprs("application/vnd.fujitsu.oasysprs", "bh2"),
    ApplicationVndFujixeroxDdd("application/vnd.fujixerox.ddd", "ddd"),
    ApplicationVndFujixeroxDocuworks("application/vnd.fujixerox.docuworks", "xdw"),
    ApplicationVndFujixeroxDocuworksBinder("application/vnd.fujixerox.docuworks.binder", "xbd"),
    ApplicationVndFuzzysheet("application/vnd.fuzzysheet", "fzs"),
    ApplicationVndGenomatixTuxedo("application/vnd.genomatix.tuxedo", "txd"),
    ApplicationVndGeogebraFile("application/vnd.geogebra.file", "ggb"),
    ApplicationVndGeogebraTool("application/vnd.geogebra.tool", "ggt"),
    ApplicationVndGeometryExplorer("application/vnd.geometry-explorer", "gex", "gre"),
    ApplicationVndGeonext("application/vnd.geonext", "gxt"),
    ApplicationVndGeoplan("application/vnd.geoplan", "g2w"),
    ApplicationVndGeospace("application/vnd.geospace", "g3w"),
    ApplicationVndGmx("application/vnd.gmx", "gmx"),
    ApplicationVndGoogleEarthKmlXml("application/vnd.google-earth.kml+xml", "kml"),
    ApplicationVndGoogleEarthKmz("application/vnd.google-earth.kmz", "kmz"),
    ApplicationVndGrafeq("application/vnd.grafeq", "gqf", "gqs"),
    ApplicationVndGrooveAccount("application/vnd.groove-account", "gac"),
    ApplicationVndGrooveHelp("application/vnd.groove-help", "ghf"),
    ApplicationVndGrooveIdentityMessage("application/vnd.groove-identity-message", "gim"),
    ApplicationVndGrooveInjector("application/vnd.groove-injector", "grv"),
    ApplicationVndGrooveToolMessage("application/vnd.groove-tool-message", "gtm"),
    ApplicationVndGrooveToolTemplate("application/vnd.groove-tool-template", "tpl"),
    ApplicationVndGrooveVcard("application/vnd.groove-vcard", "vcg"),
    ApplicationVndHalXml("application/vnd.hal+xml", "hal"),
    ApplicationVndHandheldEntertainmentXml("application/vnd.handheld-entertainment+xml", "zmm"),
    ApplicationVndHbci("application/vnd.hbci", "hbci"),
    ApplicationVndHheLessonPlayer("application/vnd.hhe.lesson-player", "les"),
    ApplicationVndHpHpgl("application/vnd.hp-hpgl", "hpgl"),
    ApplicationVndHpHpid("application/vnd.hp-hpid", "hpid"),
    ApplicationVndHpHps("application/vnd.hp-hps", "hps"),
    ApplicationVndHpJlyt("application/vnd.hp-jlyt", "jlt"),
    ApplicationVndHpPcl("application/vnd.hp-pcl", "pcl"),
    ApplicationVndHpPclxl("application/vnd.hp-pclxl", "pclxl"),
    ApplicationVndHydrostatixSofData("application/vnd.hydrostatix.sof-data", "sfd-hdstx"),
    ApplicationVndIbmMinipay("application/vnd.ibm.minipay", "mpy"),
    ApplicationVndIbmModcap("application/vnd.ibm.modcap", "afp", "listafp", "list3820"),
    ApplicationVndIbmRightsManagement("application/vnd.ibm.rights-management", "irm"),
    ApplicationVndIbmSecureContainer("application/vnd.ibm.secure-container", "sc"),
    ApplicationVndIccprofile("application/vnd.iccprofile", "icc", "icm"),
    ApplicationVndIgloader("application/vnd.igloader", "igl"),
    ApplicationVndImmervisionIvp("application/vnd.immervision-ivp", "ivp"),
    ApplicationVndImmervisionIvu("application/vnd.immervision-ivu", "ivu"),
    ApplicationVndInsorsIgm("application/vnd.insors.igm", "igm"),
    ApplicationVndInterconFormnet("application/vnd.intercon.formnet", "xpw", "xpx"),
    ApplicationVndIntergeo("application/vnd.intergeo", "i2g"),
    ApplicationVndIntuQbo("application/vnd.intu.qbo", "qbo"),
    ApplicationVndIntuQfx("application/vnd.intu.qfx", "qfx"),
    ApplicationVndIpunpluggedRcprofile("application/vnd.ipunplugged.rcprofile", "rcprofile"),
    ApplicationVndIrepositoryPackageXml("application/vnd.irepository.package+xml", "irp"),
    ApplicationVndIsacFcs("application/vnd.isac.fcs", "fcs"),
    ApplicationVndIsXpr("application/vnd.is-xpr", "xpr"),
    ApplicationVndJam("application/vnd.jam", "jam"),
    ApplicationVndJcpJavameMidletRms("application/vnd.jcp.javame.midlet-rms", "rms"),
    ApplicationVndJisp("application/vnd.jisp", "jisp"),
    ApplicationVndJoostJodaArchive("application/vnd.joost.joda-archive", "joda"),
    ApplicationVndKahootz("application/vnd.kahootz", "ktz", "ktr"),
    ApplicationVndKdeKarbon("application/vnd.kde.karbon", "karbon"),
    ApplicationVndKdeKchart("application/vnd.kde.kchart", "chrt"),
    ApplicationVndKdeKformula("application/vnd.kde.kformula", "kfo"),
    ApplicationVndKdeKivio("application/vnd.kde.kivio", "flw"),
    ApplicationVndKdeKontour("application/vnd.kde.kontour", "kon"),
    ApplicationVndKdeKpresenter("application/vnd.kde.kpresenter", "kpr", "kpt"),
    ApplicationVndKdeKspread("application/vnd.kde.kspread", "ksp"),
    ApplicationVndKdeKword("application/vnd.kde.kword", "kwd", "kwt"),
    ApplicationVndKenameaapp("application/vnd.kenameaapp", "htke"),
    ApplicationVndKidspiration("application/vnd.kidspiration", "kia"),
    ApplicationVndKinar("application/vnd.kinar", "kne", "knp"),
    ApplicationVndKoan("application/vnd.koan", "skp", "skd", "skt", "skm"),
    ApplicationVndKodakDescriptor("application/vnd.kodak-descriptor", "sse"),
    ApplicationVndLasLasXml("application/vnd.las.las+xml", "lasxml"),
    ApplicationVndLlamagraphicsLifeBalanceDesktop("application/vnd.llamagraphics.life-balance.desktop", "lbd"),
    ApplicationVndLlamagraphicsLifeBalanceExchangeXml("application/vnd.llamagraphics.life-balance.exchange+xml", "lbe"),
    ApplicationVndLotus123("application/vnd.lotus-1-2-3", "123"),
    ApplicationVndLotusApproach("application/vnd.lotus-approach", "apr"),
    ApplicationVndLotusFreelance("application/vnd.lotus-freelance", "pre"),
    ApplicationVndLotusNotes("application/vnd.lotus-notes", "nsf"),
    ApplicationVndLotusOrganizer("application/vnd.lotus-organizer", "org"),
    ApplicationVndLotusScreencam("application/vnd.lotus-screencam", "scm"),
    ApplicationVndLotusWordpro("application/vnd.lotus-wordpro", "lwp"),
    ApplicationVndMacportsPortpkg("application/vnd.macports.portpkg", "portpkg"),
    ApplicationVndMcd("application/vnd.mcd", "mcd"),
    ApplicationVndMedcalcdata("application/vnd.medcalcdata", "mc1"),
    ApplicationVndMediastationCdkey("application/vnd.mediastation.cdkey", "cdkey"),
    ApplicationVndMfer("application/vnd.mfer", "mwf"),
    ApplicationVndMfmp("application/vnd.mfmp", "mfm"),
    ApplicationVndMicrografxFlo("application/vnd.micrografx.flo", "flo"),
    ApplicationVndMicrografxIgx("application/vnd.micrografx.igx", "igx"),
    ApplicationVndMif("application/vnd.mif", "mif"),
    ApplicationVndMobiusDaf("application/vnd.mobius.daf", "daf"),
    ApplicationVndMobiusDis("application/vnd.mobius.dis", "dis"),
    ApplicationVndMobiusMbk("application/vnd.mobius.mbk", "mbk"),
    ApplicationVndMobiusMqy("application/vnd.mobius.mqy", "mqy"),
    ApplicationVndMobiusMsl("application/vnd.mobius.msl", "msl"),
    ApplicationVndMobiusPlc("application/vnd.mobius.plc", "plc"),
    ApplicationVndMobiusTxf("application/vnd.mobius.txf", "txf"),
    ApplicationVndMophunApplication("application/vnd.mophun.application", "mpn"),
    ApplicationVndMophunCertificate("application/vnd.mophun.certificate", "mpc"),
    ApplicationVndMozillaXulXml("application/vnd.mozilla.xul+xml", "xul"),
    ApplicationVndMsArtgalry("application/vnd.ms-artgalry", "cil"),
    ApplicationVndMsCabCompressed("application/vnd.ms-cab-compressed", "cab"),
    ApplicationVndMseq("application/vnd.mseq", "mseq"),
    ApplicationVndMsExcel("application/vnd.ms-excel", "xls", "xlm", "xla", "xlc", "xlt", "xlw"),
    ApplicationVndMsExcelAddinMacroenabled12("application/vnd.ms-excel.addin.macroenabled.12", "xlam"),
    ApplicationVndMsExcelSheetBinaryMacroenabled12("application/vnd.ms-excel.sheet.binary.macroenabled.12", "xlsb"),
    ApplicationVndMsExcelSheetMacroenabled12("application/vnd.ms-excel.sheet.macroenabled.12", "xlsm"),
    ApplicationVndMsExcelTemplateMacroenabled12("application/vnd.ms-excel.template.macroenabled.12", "xltm"),
    ApplicationVndMsFontobject("application/vnd.ms-fontobject", "eot"),
    ApplicationVndMsHtmlhelp("application/vnd.ms-htmlhelp", "chm"),
    ApplicationVndMsIms("application/vnd.ms-ims", "ims"),
    ApplicationVndMsLrm("application/vnd.ms-lrm", "lrm"),
    ApplicationVndMsOfficetheme("application/vnd.ms-officetheme", "thmx"),
    ApplicationVndMsPkiSeccat("application/vnd.ms-pki.seccat", "cat"),
    ApplicationVndMsPkiStl("application/vnd.ms-pki.stl", "stl"),
    ApplicationVndMsPowerpoint("application/vnd.ms-powerpoint", "ppt", "pps", "pot"),
    ApplicationVndMsPowerpointAddinMacroenabled12("application/vnd.ms-powerpoint.addin.macroenabled.12", "ppam"),
    ApplicationVndMsPowerpointPresentationMacroenabled12("application/vnd.ms-powerpoint.presentation.macroenabled.12", "pptm"),
    ApplicationVndMsPowerpointSlideMacroenabled12("application/vnd.ms-powerpoint.slide.macroenabled.12", "sldm"),
    ApplicationVndMsPowerpointSlideshowMacroenabled12("application/vnd.ms-powerpoint.slideshow.macroenabled.12", "ppsm"),
    ApplicationVndMsPowerpointTemplateMacroenabled12("application/vnd.ms-powerpoint.template.macroenabled.12", "potm"),
    ApplicationVndMsProject("application/vnd.ms-project", "mpp", "mpt"),
    ApplicationVndMsWordDocumentMacroenabled12("application/vnd.ms-word.document.macroenabled.12", "docm"),
    ApplicationVndMsWordTemplateMacroenabled12("application/vnd.ms-word.template.macroenabled.12", "dotm"),
    ApplicationVndMsWorks("application/vnd.ms-works", "wps", "wks", "wcm", "wdb"),
    ApplicationVndMsWpl("application/vnd.ms-wpl", "wpl"),
    ApplicationVndMsXpsdocument("application/vnd.ms-xpsdocument", "xps"),
    ApplicationVndMusician("application/vnd.musician", "mus"),
    ApplicationVndMuveeStyle("application/vnd.muvee.style", "msty"),
    ApplicationVndMynfc("application/vnd.mynfc", "taglet"),
    ApplicationVndNeurolanguageNlu("application/vnd.neurolanguage.nlu", "nlu"),
    ApplicationVndNitf("application/vnd.nitf", "ntf", "nitf"),
    ApplicationVndNoblenetDirectory("application/vnd.noblenet-directory", "nnd"),
    ApplicationVndNoblenetSealer("application/vnd.noblenet-sealer", "nns"),
    ApplicationVndNoblenetWeb("application/vnd.noblenet-web", "nnw"),
    ApplicationVndNokiaNGageData("application/vnd.nokia.n-gage.data", "ngdat"),
    ApplicationVndNokiaNGageSymbianInstall("application/vnd.nokia.n-gage.symbian.install", "n-gage"),
    ApplicationVndNokiaRadioPreset("application/vnd.nokia.radio-preset", "rpst"),
    ApplicationVndNokiaRadioPresets("application/vnd.nokia.radio-presets", "rpss"),
    ApplicationVndNovadigmEdm("application/vnd.novadigm.edm", "edm"),
    ApplicationVndNovadigmEdx("application/vnd.novadigm.edx", "edx"),
    ApplicationVndNovadigmExt("application/vnd.novadigm.ext", "ext"),
    ApplicationVndOasisOpendocumentChart("application/vnd.oasis.opendocument.chart", "odc"),
    ApplicationVndOasisOpendocumentChartTemplate("application/vnd.oasis.opendocument.chart-template", "otc"),
    ApplicationVndOasisOpendocumentDatabase("application/vnd.oasis.opendocument.database", "odb"),
    ApplicationVndOasisOpendocumentFormula("application/vnd.oasis.opendocument.formula", "odf"),
    ApplicationVndOasisOpendocumentFormulaTemplate("application/vnd.oasis.opendocument.formula-template", "odft"),
    ApplicationVndOasisOpendocumentGraphics("application/vnd.oasis.opendocument.graphics", "odg"),
    ApplicationVndOasisOpendocumentGraphicsTemplate("application/vnd.oasis.opendocument.graphics-template", "otg"),
    ApplicationVndOasisOpendocumentImage("application/vnd.oasis.opendocument.image", "odi"),
    ApplicationVndOasisOpendocumentImageTemplate("application/vnd.oasis.opendocument.image-template", "oti"),
    ApplicationVndOasisOpendocumentPresentation("application/vnd.oasis.opendocument.presentation", "odp"),
    ApplicationVndOasisOpendocumentPresentationTemplate("application/vnd.oasis.opendocument.presentation-template", "otp"),
    ApplicationVndOasisOpendocumentSpreadsheet("application/vnd.oasis.opendocument.spreadsheet", "ods"),
    ApplicationVndOasisOpendocumentSpreadsheetTemplate("application/vnd.oasis.opendocument.spreadsheet-template", "ots"),
    ApplicationVndOasisOpendocumentText("application/vnd.oasis.opendocument.text", "odt"),
    ApplicationVndOasisOpendocumentTextMaster("application/vnd.oasis.opendocument.text-master", "odm"),
    ApplicationVndOasisOpendocumentTextTemplate("application/vnd.oasis.opendocument.text-template", "ott"),
    ApplicationVndOasisOpendocumentTextWeb("application/vnd.oasis.opendocument.text-web", "oth"),
    ApplicationVndOlpcSugar("application/vnd.olpc-sugar", "xo"),
    ApplicationVndOmaDd2Xml("application/vnd.oma.dd2+xml", "dd2"),
    ApplicationVndOpenofficeorgExtension("application/vnd.openofficeorg.extension", "oxt"),
    ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation("application/vnd.openxmlformats-officedocument.presentationml.presentation", "pptx"),
    ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlide("application/vnd.openxmlformats-officedocument.presentationml.slide", "sldx"),
    ApplicationVndOpenxmlformatsOfficedocumentPresentationmlSlideshow("application/vnd.openxmlformats-officedocument.presentationml.slideshow", "ppsx"),
    ApplicationVndOpenxmlformatsOfficedocumentPresentationmlTemplate("application/vnd.openxmlformats-officedocument.presentationml.template", "potx"),
    ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"),
    ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlTemplate("application/vnd.openxmlformats-officedocument.spreadsheetml.template", "xltx"),
    ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument("application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx"),
    ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlTemplate("application/vnd.openxmlformats-officedocument.wordprocessingml.template", "dotx"),
    ApplicationVndOsgeoMapguidePackage("application/vnd.osgeo.mapguide.package", "mgp"),
    ApplicationVndOsgiDp("application/vnd.osgi.dp", "dp"),
    ApplicationVndOsgiSubsystem("application/vnd.osgi.subsystem", "esa"),
    ApplicationVndPalm("application/vnd.palm", "pdb", "pqa", "oprc"),
    ApplicationVndPawaafile("application/vnd.pawaafile", "paw"),
    ApplicationVndPgFormat("application/vnd.pg.format", "str"),
    ApplicationVndPgOsasli("application/vnd.pg.osasli", "ei6"),
    ApplicationVndPicsel("application/vnd.picsel", "efif"),
    ApplicationVndPmiWidget("application/vnd.pmi.widget", "wg"),
    ApplicationVndPocketlearn("application/vnd.pocketlearn", "plf"),
    ApplicationVndPowerbuilder6("application/vnd.powerbuilder6", "pbd"),
    ApplicationVndPreviewsystemsBox("application/vnd.previewsystems.box", "box"),
    ApplicationVndProteusMagazine("application/vnd.proteus.magazine", "mgz"),
    ApplicationVndPublishareDeltaTree("application/vnd.publishare-delta-tree", "qps"),
    ApplicationVndPviPtid1("application/vnd.pvi.ptid1", "ptid"),
    ApplicationVndQuarkQuarkxpress("application/vnd.quark.quarkxpress", "qxd", "qxt", "qwd", "qwt", "qxl", "qxb"),
    ApplicationVndRealvncBed("application/vnd.realvnc.bed", "bed"),
    ApplicationVndRecordareMusicxml("application/vnd.recordare.musicxml", "mxl"),
    ApplicationVndRecordareMusicxmlXml("application/vnd.recordare.musicxml+xml", "musicxml"),
    ApplicationVndRigCryptonote("application/vnd.rig.cryptonote", "cryptonote"),
    ApplicationVndRimCod("application/vnd.rim.cod", "cod"),
    ApplicationVndRnReal("application/vnd.rn-real", "rm"),
    ApplicationVndRnRealmediaVbr("application/vnd.rn-realmedia-vbr", "rmvb"),
    ApplicationVndRoute66Link66Xml("application/vnd.route66.link66+xml", "link66"),
    ApplicationVndSailingtrackerTrack("application/vnd.sailingtracker.track", "st"),
    ApplicationVndSeemail("application/vnd.seemail", "see"),
    ApplicationVndSema("application/vnd.sema", "sema"),
    ApplicationVndSemd("application/vnd.semd", "semd"),
    ApplicationVndSemf("application/vnd.semf", "semf"),
    ApplicationVndShanaInformedFormdata("application/vnd.shana.informed.formdata", "ifm"),
    ApplicationVndShanaInformedFormtemplate("application/vnd.shana.informed.formtemplate", "itp"),
    ApplicationVndShanaInformedInterchange("application/vnd.shana.informed.interchange", "iif"),
    ApplicationVndShanaInformedPackage("application/vnd.shana.informed.package", "ipk"),
    ApplicationVndSimtechMindmapper("application/vnd.simtech-mindmapper", "twd", "twds"),
    ApplicationVndSmaf("application/vnd.smaf", "mmf"),
    ApplicationVndSmartTeacher("application/vnd.smart.teacher", "teacher"),
    ApplicationVndSolentSdkmXml("application/vnd.solent.sdkm+xml", "sdkm", "sdkd"),
    ApplicationVndSpotfireDxp("application/vnd.spotfire.dxp", "dxp"),
    ApplicationVndSpotfireSfs("application/vnd.spotfire.sfs", "sfs"),
    ApplicationVndStardivisionCalc("application/vnd.stardivision.calc", "sdc"),
    ApplicationVndStardivisionDraw("application/vnd.stardivision.draw", "sda"),
    ApplicationVndStardivisionImpress("application/vnd.stardivision.impress", "sdd"),
    ApplicationVndStardivisionMath("application/vnd.stardivision.math", "smf"),
    ApplicationVndStardivisionWriter("application/vnd.stardivision.writer", "sdw", "vor"),
    ApplicationVndStardivisionWriterGlobal("application/vnd.stardivision.writer-global", "sgl"),
    ApplicationVndStepmaniaPackage("application/vnd.stepmania.package", "smzip"),
    ApplicationVndStepmaniaStepchart("application/vnd.stepmania.stepchart", "sm"),
    ApplicationVndSunXmlCalc("application/vnd.sun.xml.calc", "sxc"),
    ApplicationVndSunXmlCalcTemplate("application/vnd.sun.xml.calc.template", "stc"),
    ApplicationVndSunXmlDraw("application/vnd.sun.xml.draw", "sxd"),
    ApplicationVndSunXmlDrawTemplate("application/vnd.sun.xml.draw.template", "std"),
    ApplicationVndSunXmlImpress("application/vnd.sun.xml.impress", "sxi"),
    ApplicationVndSunXmlImpressTemplate("application/vnd.sun.xml.impress.template", "sti"),
    ApplicationVndSunXmlMath("application/vnd.sun.xml.math", "sxm"),
    ApplicationVndSunXmlWriter("application/vnd.sun.xml.writer", "sxw"),
    ApplicationVndSunXmlWriterGlobal("application/vnd.sun.xml.writer.global", "sxg"),
    ApplicationVndSunXmlWriterTemplate("application/vnd.sun.xml.writer.template", "stw"),
    ApplicationVndSusCalendar("application/vnd.sus-calendar", "sus", "susp"),
    ApplicationVndSvd("application/vnd.svd", "svd"),
    ApplicationVndSymbianInstall("application/vnd.symbian.install", "sis", "sisx"),
    ApplicationVndSyncmlDmWbxml("application/vnd.syncml.dm+wbxml", "bdm"),
    ApplicationVndSyncmlDmXml("application/vnd.syncml.dm+xml", "xdm"),
    ApplicationVndSyncmlXml("application/vnd.syncml+xml", "xsm"),
    ApplicationVndTaoIntentModuleArchive("application/vnd.tao.intent-module-archive", "tao"),
    ApplicationVndTcpdumpPcap("application/vnd.tcpdump.pcap", "pcap", "cap", "dmp"),
    ApplicationVndTmobileLivetv("application/vnd.tmobile-livetv", "tmo"),
    ApplicationVndTridTpt("application/vnd.trid.tpt", "tpt"),
    ApplicationVndTriscapeMxs("application/vnd.triscape.mxs", "mxs"),
    ApplicationVndTrueapp("application/vnd.trueapp", "tra"),
    ApplicationVndUfdl("application/vnd.ufdl", "ufd", "ufdl"),
    ApplicationVndUiqTheme("application/vnd.uiq.theme", "utz"),
    ApplicationVndUmajin("application/vnd.umajin", "umj"),
    ApplicationVndUnity("application/vnd.unity", "unityweb"),
    ApplicationVndUomlXml("application/vnd.uoml+xml", "uoml"),
    ApplicationVndVcx("application/vnd.vcx", "vcx"),
    ApplicationVndVisio("application/vnd.visio", "vsd", "vst", "vss", "vsw"),
    ApplicationVndVisionary("application/vnd.visionary", "vis"),
    ApplicationVndVsf("application/vnd.vsf", "vsf"),
    ApplicationVndWapWbxml("application/vnd.wap.wbxml", "wbxml"),
    ApplicationVndWapWmlc("application/vnd.wap.wmlc", "wmlc"),
    ApplicationVndWapWmlscriptc("application/vnd.wap.wmlscriptc", "wmlsc"),
    ApplicationVndWebturbo("application/vnd.webturbo", "wtb"),
    ApplicationVndWolframPlayer("application/vnd.wolfram.player", "nbp"),
    ApplicationVndWordperfect("application/vnd.wordperfect", "wpd"),
    ApplicationVndWqd("application/vnd.wqd", "wqd"),
    ApplicationVndWtStf("application/vnd.wt.stf", "stf"),
    ApplicationVndXara("application/vnd.xara", "xar"),
    ApplicationVndXfdl("application/vnd.xfdl", "xfdl"),
    ApplicationVndYamahaHvDic("application/vnd.yamaha.hv-dic", "hvd"),
    ApplicationVndYamahaHvScript("application/vnd.yamaha.hv-script", "hvs"),
    ApplicationVndYamahaHvVoice("application/vnd.yamaha.hv-voice", "hvp"),
    ApplicationVndYamahaOpenscoreformat("application/vnd.yamaha.openscoreformat", "osf"),
    ApplicationVndYamahaOpenscoreformatOsfpvgXml("application/vnd.yamaha.openscoreformat.osfpvg+xml", "osfpvg"),
    ApplicationVndYamahaSmafAudio("application/vnd.yamaha.smaf-audio", "saf"),
    ApplicationVndYamahaSmafPhrase("application/vnd.yamaha.smaf-phrase", "spf"),
    ApplicationVndYellowriverCustomMenu("application/vnd.yellowriver-custom-menu", "cmp"),
    ApplicationVndZul("application/vnd.zul", "zir", "zirz"),
    ApplicationVndZzazzDeckXml("application/vnd.zzazz.deck+xml", "zaz"),
    ApplicationVoicexmlXml("application/voicexml+xml", "vxml"),
    ApplicationWidget("application/widget", "wgt"),
    ApplicationWinhlp("application/winhlp", "hlp"),
    ApplicationWsdlXml("application/wsdl+xml", "wsdl"),
    ApplicationWspolicyXml("application/wspolicy+xml", "wspolicy"),
    ApplicationX7zCompressed("application/x-7z-compressed", "7z"),
    ApplicationXAbiword("application/x-abiword", "abw"),
    ApplicationXAceCompressed("application/x-ace-compressed", "ace"),
    ApplicationXamlXml("application/xaml+xml", "xaml"),
    ApplicationXAppleDiskimage("application/x-apple-diskimage", "dmg"),
    ApplicationXAuthorwareBin("application/x-authorware-bin", "aab", "x32", "u32", "vox"),
    ApplicationXAuthorwareMap("application/x-authorware-map", "aam"),
    ApplicationXAuthorwareSeg("application/x-authorware-seg", "aas"),
    ApplicationXBcpio("application/x-bcpio", "bcpio"),
    ApplicationXBittorrent("application/x-bittorrent", "torrent"),
    ApplicationXBlorb("application/x-blorb", "blb", "blorb"),
    ApplicationXBzip("application/x-bzip", "bz"),
    ApplicationXBzip2("application/x-bzip2", "bz2", "boz"),
    ApplicationXcapDiffXml("application/xcap-diff+xml", "xdf"),
    ApplicationXCbr("application/x-cbr", "cbr", "cba", "cbt", "cbz", "cb7"),
    ApplicationXCdlink("application/x-cdlink", "vcd"),
    ApplicationXCfsCompressed("application/x-cfs-compressed", "cfs"),
    ApplicationXChat("application/x-chat", "chat"),
    ApplicationXChessPgn("application/x-chess-pgn", "pgn"),
    ApplicationXConference("application/x-conference", "nsc"),
    ApplicationXCpio("application/x-cpio", "cpio"),
    ApplicationXCsh("application/x-csh", "csh"),
    ApplicationXDebianPackage("application/x-debian-package", "deb", "udeb"),
    ApplicationXDgcCompressed("application/x-dgc-compressed", "dgc"),
    ApplicationXDirector("application/x-director", "dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"),
    ApplicationXDoom("application/x-doom", "wad"),
    ApplicationXDtbncxXml("application/x-dtbncx+xml", "ncx"),
    ApplicationXDtbookXml("application/x-dtbook+xml", "dtb"),
    ApplicationXDtbresourceXml("application/x-dtbresource+xml", "res"),
    ApplicationXDvi("application/x-dvi", "dvi"),
    ApplicationXencXml("application/xenc+xml", "xenc"),
    ApplicationXEnvoy("application/x-envoy", "evy"),
    ApplicationXEva("application/x-eva", "eva"),
    ApplicationXFontBdf("application/x-font-bdf", "bdf"),
    ApplicationXFontGhostscript("application/x-font-ghostscript", "gsf"),
    ApplicationXFontLinuxPsf("application/x-font-linux-psf", "psf"),
    ApplicationXFontOtf("application/x-font-otf", "otf"),
    ApplicationXFontPcf("application/x-font-pcf", "pcf"),
    ApplicationXFontSnf("application/x-font-snf", "snf"),
    ApplicationXFontTtf("application/x-font-ttf", "ttf", "ttc"),
    ApplicationXFontType1("application/x-font-type1", "pfa", "pfb", "pfm", "afm"),
    ApplicationXFreearc("application/x-freearc", "arc"),
    ApplicationXFuturesplash("application/x-futuresplash", "spl"),
    ApplicationXGcaCompressed("application/x-gca-compressed", "gca"),
    ApplicationXGlulx("application/x-glulx", "ulx"),
    ApplicationXGnumeric("application/x-gnumeric", "gnumeric"),
    ApplicationXGrampsXml("application/x-gramps-xml", "gramps"),
    ApplicationXGtar("application/x-gtar", "gtar"),
    ApplicationXHdf("application/x-hdf", "hdf"),
    ApplicationXhtmlXml("application/xhtml+xml", "xhtml", "xht"),
    ApplicationXInstallInstructions("application/x-install-instructions", "install"),
    ApplicationXIso9660Image("application/x-iso9660-image", "iso"),
    ApplicationXJavaJnlpFile("application/x-java-jnlp-file", "jnlp"),
    ApplicationXLatex("application/x-latex", "latex"),
    ApplicationXLzhCompressed("application/x-lzh-compressed", "lzh", "lha"),
    ApplicationXMie("application/x-mie", "mie"),
    ApplicationXml("application/xml", "xml", "xsl", "xsd"),
    ApplicationXmlDtd("application/xml-dtd", "dtd"),
    ApplicationXMobipocketEbook("application/x-mobipocket-ebook", "prc", "mobi"),
    ApplicationXMsaccess("application/x-msaccess", "mdb"),
    ApplicationXMsApplication("application/x-ms-application", "application"),
    ApplicationXMsbinder("application/x-msbinder", "obd"),
    ApplicationXMscardfile("application/x-mscardfile", "crd"),
    ApplicationXMsclip("application/x-msclip", "clp"),
    ApplicationXMsdownload("application/x-msdownload", "exe", "dll", "com", "bat", "msi"),
    ApplicationXMsmediaview("application/x-msmediaview", "mvb", "m13", "m14"),
    ApplicationXMsmetafile("application/x-msmetafile", "wmf", "wmz", "emf", "emz"),
    ApplicationXMsmoney("application/x-msmoney", "mny"),
    ApplicationXMspublisher("application/x-mspublisher", "pub"),
    ApplicationXMsschedule("application/x-msschedule", "scd"),
    ApplicationXMsShortcut("application/x-ms-shortcut", "lnk"),
    ApplicationXMsterminal("application/x-msterminal", "trm"),
    ApplicationXMsWmd("application/x-ms-wmd", "wmd"),
    ApplicationXMsWmz("application/x-ms-wmz", "wmz"),
    ApplicationXMswrite("application/x-mswrite", "wri"),
    ApplicationXMsXbap("application/x-ms-xbap", "xbap"),
    ApplicationXNetcdf("application/x-netcdf", "nc", "cdf"),
    ApplicationXNzb("application/x-nzb", "nzb"),
    ApplicationXopXml("application/xop+xml", "xop"),
    ApplicationXPkcs12("application/x-pkcs12", "p12", "pfx"),
    ApplicationXPkcs7Certificates("application/x-pkcs7-certificates", "p7b", "spc"),
    ApplicationXPkcs7Certreqresp("application/x-pkcs7-certreqresp", "p7r"),
    ApplicationXprocXml("application/xproc+xml", "xpl"),
    ApplicationXRarCompressed("application/x-rar-compressed", "rar"),
    ApplicationXResearchInfoSystems("application/x-research-info-systems", "ris"),
    ApplicationXSh("application/x-sh", "sh", "bash", "bash", "profile", "tcsh", "tcshrc"),
    ApplicationXShar("application/x-shar", "shar"),
    ApplicationXShockwaveFlash("application/x-shockwave-flash", "swf"),
    ApplicationXSilverlightApp("application/x-silverlight-app", "xap"),
    ApplicationXsltXml("application/xslt+xml", "xslt"),
    ApplicationXspfXml("application/xspf+xml", "xspf"),
    ApplicationXSql("application/x-sql", "sql"),
    ApplicationXStuffit("application/x-stuffit", "sit"),
    ApplicationXStuffitx("application/x-stuffitx", "sitx"),
    ApplicationXSubrip("application/x-subrip", "srt"),
    ApplicationXSv4cpio("application/x-sv4cpio", "sv4cpio"),
    ApplicationXSv4crc("application/x-sv4crc", "sv4crc"),
    ApplicationXT3vmImage("application/x-t3vm-image", "t3"),
    ApplicationXTads("application/x-tads", "gam"),
    ApplicationXTar("application/x-tar", "tar"),
    ApplicationXTcl("application/x-tcl", "tcl"),
    ApplicationXTex("application/x-tex", "tex"),
    ApplicationXTexinfo("application/x-texinfo", "texinfo", "texi"),
    ApplicationXTexTfm("application/x-tex-tfm", "tfm"),
    ApplicationXTgif("application/x-tgif", "obj"),
    ApplicationXUstar("application/x-ustar", "ustar"),
    ApplicationXvXml("application/xv+xml", "mxml", "xhvml", "xvml", "xvm"),
    ApplicationXWaisSource("application/x-wais-source", "src"),
    ApplicationXX509CaCert("application/x-x509-ca-cert", "der", "crt"),
    ApplicationXXfig("application/x-xfig", "fig"),
    ApplicationXXliffXml("application/x-xliff+xml", "xlf"),
    ApplicationXXpinstall("application/x-xpinstall", "xpi"),
    ApplicationXXz("application/x-xz", "xz"),
    ApplicationXZmachine("application/x-zmachine", "z1", "z2", "z3", "z4", "z5", "z6", "z7", "z8"),
    ApplicationYang("application/yang", "yang"),
    ApplicationYinXml("application/yin+xml", "yin"),
    ApplicationZip("application/zip", "zip"),
    AudioAdpcm("audio/adpcm", "adp"),
    AudioBasic("audio/basic", "au", "snd"),
    AudioMidi("audio/midi", "mid", "midi", "kar", "rmi"),
    AudioMp4("audio/mp4", "mp4a"),
    AudioMpeg("audio/mpeg", "mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"),
    AudioOgg("audio/ogg", "oga", "ogg", "spx"),
    AudioS3m("audio/s3m", "s3m"),
    AudioSilk("audio/silk", "sil"),
    AudioVndDeceAudio("audio/vnd.dece.audio", "uva", "uvva"),
    AudioVndDigitalWinds("audio/vnd.digital-winds", "eol"),
    AudioVndDra("audio/vnd.dra", "dra"),
    AudioVndDts("audio/vnd.dts", "dts"),
    AudioVndDtsHd("audio/vnd.dts.hd", "dtshd"),
    AudioVndLucentVoice("audio/vnd.lucent.voice", "lvp"),
    AudioVndMsPlayreadyMediaPya("audio/vnd.ms-playready.media.pya", "pya"),
    AudioVndNueraEcelp4800("audio/vnd.nuera.ecelp4800", "ecelp4800"),
    AudioVndNueraEcelp7470("audio/vnd.nuera.ecelp7470", "ecelp7470"),
    AudioVndNueraEcelp9600("audio/vnd.nuera.ecelp9600", "ecelp9600"),
    AudioVndRip("audio/vnd.rip", "rip"),
    AudioWebm("audio/webm", "weba"),
    AudioXAac("audio/x-aac", "aac"),
    AudioXAiff("audio/x-aiff", "aif", "aiff", "aifc"),
    AudioXCaf("audio/x-caf", "caf"),
    AudioXFlac("audio/x-flac", "flac"),
    AudioXm("audio/xm", "xm"),
    AudioXMatroska("audio/x-matroska", "mka"),
    AudioXMpegurl("audio/x-mpegurl", "m3u"),
    AudioXMsWax("audio/x-ms-wax", "wax"),
    AudioXMsWma("audio/x-ms-wma", "wma"),
    AudioXPnRealaudio("audio/x-pn-realaudio", "ram", "ra"),
    AudioXPnRealaudioPlugin("audio/x-pn-realaudio-plugin", "rmp"),
    AudioXWav("audio/x-wav", "wav"),
    ChemicalXCdx("chemical/x-cdx", "cdx"),
    ChemicalXCif("chemical/x-cif", "cif"),
    ChemicalXCmdf("chemical/x-cmdf", "cmdf"),
    ChemicalXCml("chemical/x-cml", "cml"),
    ChemicalXCsml("chemical/x-csml", "csml"),
    ChemicalXXyz("chemical/x-xyz", "xyz"),
    ImageBmp("image/bmp", "bmp"),
    ImageCgm("image/cgm", "cgm"),
    ImageG3fax("image/g3fax", "g3"),
    ImageGif("image/gif", "gif"),
    ImageIef("image/ief", "ief"),
    ImageJpeg("image/jpeg", "jpeg", "jpg", "jpe"),
    ImageKtx("image/ktx", "ktx"),
    ImagePng("image/png", "png"),
    ImagePrsBtif("image/prs.btif", "btif"),
    ImageSgi("image/sgi", "sgi"),
    ImageSvgXml("image/svg+xml", "svg", "svgz"),
    ImageTiff("image/tiff", "tiff", "tif"),
    ImageVndAdobePhotoshop("image/vnd.adobe.photoshop", "psd"),
    ImageVndDeceGraphic("image/vnd.dece.graphic", "uvi", "uvvi", "uvg", "uvvg"),
    ImageVndDjvu("image/vnd.djvu", "djvu", "djv"),
    ImageVndDvbSubtitle("image/vnd.dvb.subtitle", "sub"),
    ImageVndDwg("image/vnd.dwg", "dwg"),
    ImageVndDxf("image/vnd.dxf", "dxf"),
    ImageVndFastbidsheet("image/vnd.fastbidsheet", "fbs"),
    ImageVndFpx("image/vnd.fpx", "fpx"),
    ImageVndFst("image/vnd.fst", "fst"),
    ImageVndFujixeroxEdmicsMmr("image/vnd.fujixerox.edmics-mmr", "mmr"),
    ImageVndFujixeroxEdmicsRlc("image/vnd.fujixerox.edmics-rlc", "rlc"),
    ImageVndMsModi("image/vnd.ms-modi", "mdi"),
    ImageVndMsPhoto("image/vnd.ms-photo", "wdp"),
    ImageVndNetFpx("image/vnd.net-fpx", "npx"),
    ImageVndWapWbmp("image/vnd.wap.wbmp", "wbmp"),
    ImageVndXiff("image/vnd.xiff", "xif"),
    ImageWebp("image/webp", "webp"),
    ImageX3ds("image/x-3ds", "3ds"),
    ImageXCmuRaster("image/x-cmu-raster", "ras"),
    ImageXCmx("image/x-cmx", "cmx"),
    ImageXFreehand("image/x-freehand", "fh", "fhc", "fh4", "fh5", "fh7"),
    ImageXIcon("image/x-icon", "ico"),
    ImageXMrsidImage("image/x-mrsid-image", "sid"),
    ImageXPcx("image/x-pcx", "pcx"),
    ImageXPict("image/x-pict", "pic", "pct"),
    ImageXPortableAnymap("image/x-portable-anymap", "pnm"),
    ImageXPortableBitmap("image/x-portable-bitmap", "pbm"),
    ImageXPortableGraymap("image/x-portable-graymap", "pgm"),
    ImageXPortablePixmap("image/x-portable-pixmap", "ppm"),
    ImageXRgb("image/x-rgb", "rgb"),
    ImageXTga("image/x-tga", "tga"),
    ImageXXbitmap("image/x-xbitmap", "xbm"),
    ImageXXpixmap("image/x-xpixmap", "xpm"),
    ImageXXwindowdump("image/x-xwindowdump", "xwd"),
    MessageRfc822("message/rfc822", "eml", "mime"),
    ModelIges("model/iges", "igs", "iges"),
    ModelMesh("model/mesh", "msh", "mesh", "silo"),
    ModelVndColladaXml("model/vnd.collada+xml", "dae"),
    ModelVndDwf("model/vnd.dwf", "dwf"),
    ModelVndGdl("model/vnd.gdl", "gdl"),
    ModelVndGtw("model/vnd.gtw", "gtw"),
    ModelVndMts("model/vnd.mts", "mts"),
    ModelVndVtu("model/vnd.vtu", "vtu"),
    ModelVrml("model/vrml", "wrl", "vrml"),
    ModelX3dBinary("model/x3d+binary", "x3db", "x3dbz"),
    ModelX3dVrml("model/x3d+vrml", "x3dv", "x3dvz"),
    ModelX3dXml("model/x3d+xml", "x3d", "x3dz"),
    TextCacheManifest("text/cache-manifest", "appcache"),
    TextCalendar("text/calendar", "ics", "ifb"),
    TextCss("text/css", "css"),
    TextCsv("text/csv", "csv"),
    TextHtml("text/html", "html", "htm"),
    TextN3("text/n3", "n3"),
    TextPlain("text/plain", "txt", "text", "conf", "def", "list", "log", "in", "properties"),
    TextPrsLinesTag("text/prs.lines.tag", "dsc"),
    TextRichtext("text/richtext", "rtx"),
    TextSgml("text/sgml", "sgml", "sgm"),
    TextTabSeparatedValues("text/tab-separated-values", "tsv"),
    TextTroff("text/troff", "t", "tr", "roff", "man", "me", "ms"),
    TextTurtle("text/turtle", "ttl"),
    TextUriList("text/uri-list", "uri", "uris", "urls"),
    TextVcard("text/vcard", "vcard"),
    TextVndCurl("text/vnd.curl", "curl"),
    TextVndCurlDcurl("text/vnd.curl.dcurl", "dcurl"),
    TextVndCurlMcurl("text/vnd.curl.mcurl", "mcurl"),
    TextVndCurlScurl("text/vnd.curl.scurl", "scurl"),
    TextVndDvbSubtitle("text/vnd.dvb.subtitle", "sub"),
    TextVndFly("text/vnd.fly", "fly"),
    TextVndFmiFlexstor("text/vnd.fmi.flexstor", "flx"),
    TextVndGraphviz("text/vnd.graphviz", "gv"),
    TextVndIn3d3dml("text/vnd.in3d.3dml", "3dml"),
    TextVndIn3dSpot("text/vnd.in3d.spot", "spot"),
    TextVndSunJ2meAppDescriptor("text/vnd.sun.j2me.app-descriptor", "jad"),
    TextVndWapWml("text/vnd.wap.wml", "wml"),
    TextVndWapWmlscript("text/vnd.wap.wmlscript", "wmls"),
    TextXAsm("text/x-asm", "s", "asm"),
    TextXC("text/x-c", "c", "cc", "cxx", "cpp", "h", "hh", "dic"),
    TextXFortran("text/x-fortran", "f", "for", "f77", "f90"),
    TextXJavaSource("text/x-java-source", "java"),
    TextXNfo("text/x-nfo", "nfo"),
    TextXOpml("text/x-opml", "opml"),
    TextXPascal("text/x-pascal", "p", "pas"),
    TextXSetext("text/x-setext", "etx"),
    TextXSfv("text/x-sfv", "sfv"),
    TextXUuencode("text/x-uuencode", "uu"),
    TextXVcalendar("text/x-vcalendar", "vcs"),
    TextXVcard("text/x-vcard", "vcf"),
    Video3gpp("video/3gpp", "3gp"),
    Video3gpp2("video/3gpp2", "3g2"),
    VideoH261("video/h261", "h261"),
    VideoH263("video/h263", "h263"),
    VideoH264("video/h264", "h264"),
    VideoJpeg("video/jpeg", "jpgv"),
    VideoJpm("video/jpm", "jpm", "jpgm"),
    VideoMj2("video/mj2", "mj2", "mjp2"),
    VideoMp4("video/mp4", "mp4", "mp4v", "mpg4"),
    VideoMpeg("video/mpeg", "mpeg", "mpg", "mpe", "m1v", "m2v"),
    VideoOgg("video/ogg", "ogv"),
    VideoQuicktime("video/quicktime", "qt", "mov"),
    VideoVndDeceHd("video/vnd.dece.hd", "uvh", "uvvh"),
    VideoVndDeceMobile("video/vnd.dece.mobile", "uvm", "uvvm"),
    VideoVndDecePd("video/vnd.dece.pd", "uvp", "uvvp"),
    VideoVndDeceSd("video/vnd.dece.sd", "uvs", "uvvs"),
    VideoVndDeceVideo("video/vnd.dece.video", "uvv", "uvvv"),
    VideoVndDvbFile("video/vnd.dvb.file", "dvb"),
    VideoVndFvt("video/vnd.fvt", "fvt"),
    VideoVndMpegurl("video/vnd.mpegurl", "mxu", "m4u"),
    VideoVndMsPlayreadyMediaPyv("video/vnd.ms-playready.media.pyv", "pyv"),
    VideoVndUvvuMp4("video/vnd.uvvu.mp4", "uvu", "uvvu"),
    VideoVndVivo("video/vnd.vivo", "viv"),
    VideoWebm("video/webm", "webm"),
    VideoXF4v("video/x-f4v", "f4v"),
    VideoXFli("video/x-fli", "fli"),
    VideoXFlv("video/x-flv", "flv"),
    VideoXM4v("video/x-m4v", "m4v"),
    VideoXMatroska("video/x-matroska", "mkv", "mk3d", "mks"),
    VideoXMng("video/x-mng", "mng"),
    VideoXMsAsf("video/x-ms-asf", "asf", "asx"),
    VideoXMsvideo("video/x-msvideo", "avi"),
    VideoXMsVob("video/x-ms-vob", "vob"),
    VideoXMsWm("video/x-ms-wm", "wm"),
    VideoXMsWmv("video/x-ms-wmv", "wmv"),
    VideoXMsWmx("video/x-ms-wmx", "wmx"),
    VideoXMsWvx("video/x-ms-wvx", "wvx"),
    VideoXSgiMovie("video/x-sgi-movie", "movie"),
    VideoXSmv("video/x-smv", "smv"),
    XConferenceXCooltalk("x-conference/x-cooltalk", "ice");

    private final String mimeType;
    private final String mimeSubtype;
    private final MediaType mediaType;
    private final Set<String> extensionSet;

    private static Map<String, Media> mediaMap;
    private static Map<String, Media> mediaExtensionMap;

    private Media(String mimeType, String... extensions) {
        this.mimeType = mimeType.trim();
        mimeSubtype = this.mimeType.split("/")[1].trim();
        TreeSet<String> set = new TreeSet<>(String.CASE_INSENSITIVE_ORDER);
        set.addAll(Arrays.asList(extensions));
        extensionSet = Collections.unmodifiableSet(set);
        mediaType = MediaType.getMediaType(mimeType);
        mediaType.addSubtype(mimeSubtype);
    }

    public String getMimeType() {
        return mimeType;
    }

    public String getMimeSubtype() {
        return mimeSubtype;
    }

    public Set<String> getExtensionSet() {
        return extensionSet;
    }

    public MediaType getMediaType() {
        return mediaType;
    }

    public static Media getMediaByExtension(String extension) {
        return getMediaExtensionMap().get(extension);
    }

    static Map<String, Media> getMediaExtensionMap() {
        if (mediaExtensionMap == null) {
            mediaExtensionMap = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
            for (Media media : values()) {
                for (String ext : media.extensionSet) {
                    mediaExtensionMap.put(ext, media);
                }
            }
        }

        return mediaExtensionMap;
    }

    public static Set<String> getMediaExtensionSet() {
        return getMediaExtensionMap().keySet();
    }

    public static Media getMedia(Path path) {
        Path file;
        if ((file = path.getFileName()) != null) {
            String fileName = file.toString();
            int dotIndex;
            if ((dotIndex = fileName.lastIndexOf('.')) >= 0 && (dotIndex + 1) < fileName.length()) {
                String fileExt = fileName.substring(dotIndex + 1).trim();
                return getMediaByExtension(fileExt);
            }
        }

        return null;
    }

    public static Media getMedia(String mimeType) {
        return getMediaMap().get(mimeType);
    }

    static Map<String, Media> getMediaMap() {
        if (mediaMap == null) {
            mediaMap = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
            for (Media media : values()) {
                mediaMap.put(media.mimeType, media);
            }
        }

        return mediaMap;
    }
}
